// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZVYYP6Y_924_tGndLzug4sI67eH9nK4',
    appId: '1:613438137013:web:62c5d78bd50d7c4e6814fc',
    messagingSenderId: '613438137013',
    projectId: 'workouttracker-45066',
    authDomain: 'workouttracker-45066.firebaseapp.com',
    storageBucket: 'workouttracker-45066.firebasestorage.app',
    measurementId: 'G-N6NPC15444',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDST8ij3keEuN8xY1Iy5Q4KDZGk7pWf9rY',
    appId: '1:613438137013:android:52c025856421cdfe6814fc',
    messagingSenderId: '613438137013',
    projectId: 'workouttracker-45066',
    storageBucket: 'workouttracker-45066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWtl2hFyWNIvahaD1iyiCTMes7r9y2i4U',
    appId: '1:613438137013:ios:4fb5893183f4f6b96814fc',
    messagingSenderId: '613438137013',
    projectId: 'workouttracker-45066',
    storageBucket: 'workouttracker-45066.firebasestorage.app',
    iosBundleId: 'com.example.applicationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWtl2hFyWNIvahaD1iyiCTMes7r9y2i4U',
    appId: '1:613438137013:ios:4fb5893183f4f6b96814fc',
    messagingSenderId: '613438137013',
    projectId: 'workouttracker-45066',
    storageBucket: 'workouttracker-45066.firebasestorage.app',
    iosBundleId: 'com.example.applicationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpZVYYP6Y_924_tGndLzug4sI67eH9nK4',
    appId: '1:613438137013:web:c31be5d6b83d0d7c6814fc',
    messagingSenderId: '613438137013',
    projectId: 'workouttracker-45066',
    authDomain: 'workouttracker-45066.firebaseapp.com',
    storageBucket: 'workouttracker-45066.firebasestorage.app',
    measurementId: 'G-MVHKYSF02T',
  );

}